### ISSUE TITLE
Why not use the estimate K from Stage 2 for Stage 1?

### ISSUE THREAD

**Issue by Gy915** [zhang-yu-wei/ClusterLLM#1]

**Comment by Gy915** [comment]
Hi, I am really interested in ClusterLLM. I'm confused about a point. As the experimental detail said, to determine the cluster number K in Stage 1 for formula (2), you set the fixed threshold as 67 for agglomerative clustering to get the cluster number. 
However, Stage 2 seems to provide a powerful method to estimate the cluster number K, and the 2 stages seem to decouple. So what consideration behind that does not use the K from Stage 2 for Stage 1?

**Comment by zhang-yu-wei** [comment]
Hi,

Thanks for your interest to our paper and sorry for a late reply.

This is a good question. We have several considerations: (1) The estimation of cluster number is also depended on the clustering quality, so that we wanted to improve the clustering quality first. (2) The estimation of cluster number is depended on human labels which might affect the comparison with other algorithms. However, in practical applications, it is possible to estimate cluster granularity first.
